name: ssh_socks_proxy
description: SSH SOCKS5 Proxy Manager for Android
publish_to: 'none'
version: 5.0.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.9.0
  shared_preferences: ^2.2.0
  flutter_background_service: ^5.0.5
  connectivity_plus: ^6.0.0
  provider: ^6.1.0
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
